### ISSUE TITLE
eachDefaultSystem leads to missing architecture attributes

### ISSUE THREAD

**Issue by holzingk** [numtide/flake-utils#114]
When I run the [eachDefaultSystem example](https://github.com/numtide/flake-utils/blob/main/examples/each-system/flake.nix) with `nix develop` I get:
```
error: flake 'git+file:///...' does not provide attribute 'devShells.x86_64-linux.devShell.x86_64-linux', 'packages.x86_64-linux.devShell.x86_64-linux', 'legacyPackages.x86_64-linux.devShell.x86_64-linux', 'devShell.x86_64-linux' or 'defaultPackage.x86_64-linux'
```

I am using nix through home manager on opensuse Tumbleweed

**Comment by zimbatm** [comment]
Try adding a `devShells.default = pkgs.mkShell { };` on the same level as the packages and apps entries.

**Comment by holzingk** [comment]
Ok. Now I have

```nix
{
  description = "Flake utils demo";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system}; in
      {
        devShells.default = pkgs.mkShell { };
        packages = rec {
          hello = pkgs.hello;
          default = hello;
        };
        apps = rec {
          hello = flake-utils.lib.mkApp { drv = self.packages.${system}.hello; };
          default = hello;
        };
      }
    );
}
```

Still gives me the same error.

**Comment by zimbatm** [comment]
Make sure you have Nix > 2.18: `nix --version` or replace the line with `devShell = pkgs.mkShell { };` (which is deprecated now)

**Comment by holzingk** [comment]
After the upgrade the issue is gone. Thanks!

Maybe a minimum version should be mentioned in the README somewhere.
