### ISSUE TITLE
utility app to `mkApp` self.packages automatically

### ISSUE THREAD

**Issue by nrdxp** [numtide/flake-utils#17]
I am basically doing this already [here](https://github.com/nrdxp/nixflk/blob/41e3de0eab833efb1d5bc44346956a705bcc13bf/flake.nix#L88-L104), but I wonder if there is a better way to do it that could be generalized so we could call it on a flakes packages output.

Essentially I am checking if a derivation has a `bin` directory in its outpath, and if so, calling mkApp on it. This requires building the derivation, which will fail on other systems, so I perform the check only on the version of the package for the currently running system.

Hopefully this can be simplified and omptimized.

**Comment by zimbatm** [comment]
The whole `apps` and `mkApp` has become somewhat redundant. Historically, `nix run` was relying on that construct to run things. Since then It has acquired its own heuristic and can lookup the `packages` and `legacyPackages`. You can try this out by running `nix run nixpkgs#hello`. So I would just expose the packages and let deal with resolving the right one.

One case where I think `mkApp` is still useful, is when a derivation output contains multiple binaries. For example, you might have `yourflake#coreutils` and also want to expose `yourflake#ls` and yourflake#mkdir`. In that case, I expect the correspondence to be drawn manually.

**Comment by nrdxp** [comment]
Without an app declaration, `nix run` seems to call the value of `name` by default to evoke the binary, which in a lot of cases is "${name}-{pname}". There is an  effort to standardize this. NixOS/nixpkgs#103997. In particular, it [fails](https://github.com/nrdxp/nixflk/blob/b7016c8d92a132c2e4d63861ac0357bc9f994a3a/pkgs/misc/drivers/wii-u-gc-adapter/default.nix) for me.

 We should probably call a package by its `pname` instead. NixOS/nix#4422

**Comment by zimbatm** [comment]
Do you want to do something about this? I think the conclusion of https://github.com/NixOS/nix/issues/4422#issuecomment-753841822 might apply here as well.

**Comment by blaggacao** [comment]
It seems I'm just hitting this:

```console
$ nix run .#CashBoxy:exe:Main
warning: Git tree '/home/blaggacao/ghq/git.p1.rocks/SideProjects/CashBoxy' is dirty
trace: gitSource.nix: /nix/store/bbln8w5gf3fainh1206f42q4zry0gmgi-source does not seem to be a git repository,
assuming it is a clean checkout.
trace: To materialize project.plan-nix for CashBoxy entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
error: --- SysError ----------------------------------------------------------------------------------- nix
unable to execute '/nix/store/baskvl2ay7mrprgjaq75w5ndclxp39m5-CashBoxy-exe-Main-0.1.0.0/bin/CashBoxy-exe-Main': No such file or directory
```

But 
```
$ ls /nix/store/baskvl2ay7mrprgjaq75w5ndclxp39m5-CashBoxy-exe-Main-0.1.0.0/bin
Main
```

so its `/bin/Main` vs `bin/CashBoxy-exe-Main`

It's all new to me, but I conclude that `program = v.exePath` still has it's validity?

**Comment by nrdxp** [comment]
If any similar issues arise in the future, they should be routed to upstream `nix` to improve the hueristic for launching packages.
