### ISSUE TITLE
simpleFlake to support defaultSystems

### ISSUE THREAD

**Issue by garethstokes** [numtide/flake-utils#54]
**Is your feature request related to a problem? Please describe.**

The instructions for using simpleFlake do not work on OSX. I followed the instructions in the README and used the example project. 

This is due to the default value for systems to be [ "x86_64-linux" ]. In order to get it working I added a single line to set the systems attribute in my flake.nix to point to `defaultSystems` instead. 

It would be good if OSX was supported out the box. 

**Describe the solution you'd like**

Change the code to have this value be defaulted to `defaultSystems`. 

**Describe alternatives you've considered**

Update the README to include an OSX friendly example

```
{
  description = "osx-example";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.simpleFlake {
      inherit self nixpkgs;
      name = "osx-example";
      systems = flake-utils.lib.defaultSystems;
      overlay = ./nix/overlay.nix;
      shell = ./nix/shell.nix;
    };
}
```

**Comment by jessestricker** [comment]
I've seen that #57 is merged, does that solve this issue?

**Comment by zimbatm** [comment]
almost. Now it does :)
