### ISSUE TITLE
flake-utils.lib.mkApp is broken with nix 2.8

### ISSUE THREAD

**Issue by Lunarequest** [numtide/flake-utils#61]
**Describe the bug**

**To Reproduce**

1. use `nix run` on a repo with the an app made with `flake-utils.lib.mkApp`
2. errors with `error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'`

**Expected behavior**
the app executes normally

**System information**
nix 2.8.0 linux

**Additional context**
nix 2.8.0 has more strictness the nix 2.7 which has broken flake-utils

**Comment by zimbatm** [comment]
is that fixed?

**Comment by TristanCacqueray** [comment]
This issue is still happening when using `defaultApp = flake-utils.lib.mkApp { drv = package; };` with nix-2.8 .
Though, without flake-utils, this works with nix-2.8:

```nix
{
  outputs = {self}:
  {
    defaultApp."${system}" = {
      type = "app";
      program = "${package}/bin/test";
    };
  };
}
```

**Comment by johnrichardrinehart** [comment]
I have a bunch of files in `$out/bin` and trying to select only one with `exePath` or `name` fails with the above error.
```nix
        apps.defaultApp =  flake-utils.lib.mkApp { drv = packages.go_1_18-fips;  name = "go";};
 ```
However, the below works just fine as `nix run .#go_1_18-fips`
```nix
        apps.go_1_18-fips = flake-utils.lib.mkApp { drv = packages.go_1_18-fips;  name = "go";};
```
