### ISSUE TITLE
nixops support

### ISSUE THREAD

**Issue by dzmitry-lahoda** [numtide/flake-utils#77]
**Is your feature request related to a problem? Please describe.**

When I put `nixops` under `forEachSystem` it stops to work. How can it be made to work?

**Describe the solution you'd like**

Likely `nixops` should be pushed up, may be something like is done with `hydra` so it works well. 

**Describe alternatives you've considered**

I am trying to override input via ad hoc flake-utils in our ci to retain only x86-64_linux ops and handle nixops well.

Also trying to make nixops // flake-utils... . Problem is that nixops depends on flake-utils build. 

**Additional context**

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/757125/182025627-a2d59e2f-7652-42cf-9c36-7a7cb3222816.png">

**Comment by zimbatm** [comment]
If you want, this is something we can offer professional support for: https://numtide.com/contact . It looks like an issue where the nix code needs to be aligned, and I would have to dig into your project's code for a while to connect things.

**Comment by dzmitry-lahoda** [comment]
you are right. this should be nixops issue to allow send system into tool. we have some workarounds

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/757125/182137567-b20fe88e-4bbe-476e-ba69-1f4069f1d037.png">

**Comment by dzmitry-lahoda** [comment]
@zimbatm issue is linked into our gh and also i think this should be fixed by nixops after your comment. so our leads may contact for consulting or we will raise issue onto nixops.

so your tool are of greate use to me, so if you will create DOT wallet I will transfer here some amount of donate.

**Comment by zimbatm** [comment]
hey, thanks for the offer. You finding it useful is enough reward for me. Just think of us if you need commercial support around nix and DevOps :)
