### ISSUE TITLE
master rename to main breaks nix flake update

### ISSUE THREAD

**Issue by numinit** [numtide/flake-utils#88]
**Describe the bug**

nix flake update on existing flakes is broken since branch rename to main

**To Reproduce**

inputs.flake-utils.url = github:numtide/flake-utils/master;

```
$ nix flake update
error: unable to download 'https://api.github.com/repos/numtide/flake-utils/commits/master': HTTP error 422

       response body:

       {
         "message": "No commit found for SHA: master",
         "documentation_url": "https://docs.github.com/rest/commits/commits#get-a-commit"
       }
(use '--show-trace' to show detailed location information)
```

**Expected behavior**

Update functions

**System information**

NixOS 22.11

**Additional context**

This is a backwards compat issue as it breaks existing flake.nix that used master branch instead of main.

**Comment by numinit** [comment]
Fixed with some use of grep and sed. Is the value of not specifying a branch in a flake input documented somewhere clear? (i.e. does it use the default branch per github, which would make this compat issue go away?)

**Comment by zimbatm** [comment]
I should have known that renaming the branch would have broken something :face_with_spiral_eyes: 

The best is to remove the `/master` entirely, as flake will pick the default branch, just like git would.

**Comment by numinit** [comment]
Thanks!
